#!/bin/sh

set -e

# This script will finish the setup of xfstt after it is
# installed. 

#DEBHELPER#

# check and see if /var/ttfonts exists - warn if it does else warn about
# "this program does not install fonts"

if [ -e "/var/ttfonts" ]; then
	echo "NOTICE: It appears you have installed fonts in 
/var/ttfonts from a previous version of xfstt. This has been changed and
xfstt now uses /usr/share/fonts/truetype. Please place any truetype fonts
in that location\n" 
	echo "Please Hit enter to continue"
	read junk
fi

	
