#!/bin/sh
# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d xfstt remove >/dev/null
	rm -rf /var/cache/xfstt/
fi

if [ "$1" = "remove" ] ; then
        rm -rf /var/cache/xfstt/
fi

# End automatically added section
#DEBHELPER#
